name: opencap-services
services:
  postgres:
    image: postgres:15
    ports:
      - 54322:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=opencap
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opencap
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  db_data: